apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nagios-pvc
spec:
  storageClassName: ""  # empty for pre-provisioned Persistent Volume
  # see Storage classes for dynamic provisioning: kubectl get sc
  accessModes:
    - ReadOnlyMany  # #the volume can be mounted read-only by many nodes
  resources:
    requests:
      storage: 10M

